version: 2

builds:
  - ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "pinchtab-{{.Os}}-{{.Arch}}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: pinchtab
    name: pinchtab
